[General]
__userfile__=true
enableBatteryWatcher=true
enableExtMonLidClosedActions=false
enableIdlenessWatcher=true
enableLidWatcher=true
idlenessAction=4
idlenessTimeSecs=3600
lidClosedAcAction=4
lidClosedAction=4
lidClosedExtMonAcAction=4
lidClosedExtMonAction=4
powerLowAction=-1
powerLowLevel=7
powerLowWarning=60
runCheckLevel=1
showIcon=true
useThemeIcons=true
