<?xml version="1.0" encoding="UTF-8"?>

<!-- Do not edit this file, it will be overwritten on install.
        Copy the file to $HOME/.config/openbox/ instead. -->

<openbox_config xmlns="http://openbox.org/3.4/rc">

<resistance>
  <strength>10</strength>
  <screen_edge_strength>20</screen_edge_strength>
</resistance>

<focus>
  <focusNew>yes</focusNew>
  <!-- always try to focus new windows when they appear. other rules do
       apply -->
  <followMouse>yes</followMouse>
  <!-- move focus to a window when you move the mouse into it -->
  <focusLast>yes</focusLast>
  <!-- focus the last used window when changing desktops, instead of the one
       under the mouse pointer. when followMouse is enabled -->
  <underMouse>no</underMouse>
  <!-- move focus under the mouse, even when the mouse is not moving -->
  <focusDelay>50</focusDelay>
  <!-- when followMouse is enabled, the mouse must be inside the window for
       this many milliseconds (1000 = 1 sec) before moving focus to it -->
  <raiseOnFocus>no</raiseOnFocus>
  <!-- when followMouse is enabled, and a window is given focus by moving the
       mouse into it, also raise the window -->
</focus>

<placement>
  <policy>Smart</policy>
  <!-- 'Smart' or 'UnderMouse' -->
  <center>no</center>
  <!-- whether to place windows in the center of the free area found or
       the top left corner -->
  <monitor>active</monitor>
  <!-- with Smart placement on a multi-monitor system, try to place new windows
       on: 'Any' - any monitor, 'Mouse' - where the mouse is, 'Active' - where
       the active window is -->
    <primaryMonitor>2</primaryMonitor>
    <!-- The monitor where Openbox should place popup dialogs such as the
       focus cycling popup, or the desktop switch popup.  It can be an index
       from 1, specifying a particular monitor.  Or it can be one of the
       following: 'Mouse' - where the mouse is, or
                  'Active' - where the active window is -->
</placement>

<theme>
  <name>Onyx</name>
  <titleLayout>NLIMC</titleLayout>
  <!--
      available characters are NDSLIMC, each can occur at most once.
      N: window icon
      L: window label (AKA title).
      I: iconify
      M: maximize
      C: close
      S: shade (roll up/down)
      D: omnipresent (on all desktops).
  -->
  <keepBorder>yes</keepBorder>
  <animateIconify>yes</animateIconify>
  <font place="ActiveWindow">
    <name>sans</name>
    <size>10</size>
    <!-- font size in points -->
    <weight>bold</weight>
    <!-- 'bold' or 'normal' -->
    <slant>normal</slant>
    <!-- 'italic' or 'normal' -->
  </font>
  <font place="InactiveWindow">
    <name>sans</name>
    <size>10</size>
    <!-- font size in points -->
    <weight>bold</weight>
    <!-- 'bold' or 'normal' -->
    <slant>normal</slant>
    <!-- 'italic' or 'normal' -->
  </font>
  <font place="MenuHeader">
    <name>sans</name>
    <size>10</size>
    <!-- font size in points -->
    <weight>normal</weight>
    <!-- 'bold' or 'normal' -->
    <slant>normal</slant>
    <!-- 'italic' or 'normal' -->
  </font>
  <font place="MenuItem">
    <name>sans</name>
    <size>10</size>
    <!-- font size in points -->
    <weight>normal</weight>
    <!-- 'bold' or 'normal' -->
    <slant>normal</slant>
    <!-- 'italic' or 'normal' -->
  </font>
  <font place="OnScreenDisplay">
    <name>sans</name>
    <size>10</size>
    <!-- font size in points -->
    <weight>bold</weight>
    <!-- 'bold' or 'normal' -->
    <slant>normal</slant>
    <!-- 'italic' or 'normal' -->
  </font>
  <font place="ActiveOnScreenDisplay">
    <name>Sans</name>
    <size>8</size>
    <weight/>
    <slant/>
  </font>
  <font place="InactiveOnScreenDisplay">
    <name>Sans</name>
    <size>8</size>
    <weight/>
    <slant/>
  </font>
</theme>

<desktops>
  <!-- this stuff is only used at startup, pagers allow you to change them
       during a session

       these are default values to use when other ones are not already set
       by other applications, or saved in your session

       use obconf if you want to change these without having to log out
       and back in -->
  <number>2</number>
  <firstdesk>1</firstdesk>
  <names>
    <!-- set names up here if you want to, like this: -->
  <name>write</name>
  <name>browse</name>
  </names>
  <popupTime>875</popupTime>
  <!-- The number of milliseconds to show the popup for when switching
       desktops.  Set this to 0 to disable the popup. -->
</desktops>

<resize>
  <drawContents>yes</drawContents>
  <popupShow>Nonpixel</popupShow>
  <!-- 'Always', 'Never', or 'Nonpixel' (xterms and such) -->
  <popupPosition>Center</popupPosition>
  <!-- 'Center', 'Top', or 'Fixed' -->
  <popupFixedPosition>
    <!-- these are used if popupPosition is set to 'Fixed' -->

    <x>10</x>
    <!-- positive number for distance from left edge, negative number for
         distance from right edge, or 'Center' -->
    <y>10</y>
    <!-- positive number for distance from top edge, negative number for
         distance from bottom edge, or 'Center' -->
  </popupFixedPosition>
</resize>

<!-- You can reserve a portion of your screen where windows will not cover when
     they are maximized, or when they are initially placed.
     Many programs reserve space automatically, but you can use this in other
     cases. -->
<margins>
  <top>0</top>
  <bottom>0</bottom>
  <left>0</left>
  <right>0</right>
</margins>

<dock>
  <position>TopLeft</position>
  <!-- (Top|Bottom)(Left|Right|)|Top|Bottom|Left|Right|Floating -->
  <floatingX>0</floatingX>
  <floatingY>0</floatingY>
  <noStrut>no</noStrut>
  <stacking>Above</stacking>
  <!-- 'Above', 'Normal', or 'Below' -->
  <direction>Vertical</direction>
  <!-- 'Vertical' or 'Horizontal' -->
  <autoHide>no</autoHide>
  <hideDelay>300</hideDelay>
  <!-- in milliseconds (1000 = 1 second) -->
  <showDelay>300</showDelay>
  <!-- in milliseconds (1000 = 1 second) -->
  <moveButton>Middle</moveButton>
  <!-- 'Left', 'Middle', 'Right' -->
</dock>

<keyboard>
  <chainQuitKey>C-g</chainQuitKey>

  <!-- Keybindings for desktop switching -->
  <keybind key="C-A-Left">          # move to desktop left
    <action name="DesktopLeft"><dialog>no</dialog><wrap>no</wrap></action>
  </keybind>
    <keybind key="W-p">               # move to desktop left (previous)
    <action name="DesktopLeft"><dialog>no</dialog><wrap>no</wrap></action>
  </keybind>
    <keybind key="C-A-Right">         # move to desktop right
    <action name="DesktopRight"><dialog>no</dialog><wrap>no</wrap></action>
  </keybind>
    <keybind key="W-n">               # move to desktop right (next)
    <action name="DesktopRight"><dialog>no</dialog><wrap>no</wrap></action>
  </keybind>
    <keybind key="C-A-Up">            # move to desktop above
    <action name="DesktopUp"><dialog>no</dialog><wrap>no</wrap></action>
  </keybind>
    <keybind key="C-A-Down">          # move to desktop below
    <action name="DesktopDown"><dialog>no</dialog><wrap>no</wrap></action>
  </keybind>
    <keybind key="S-A-Left">          # send window to desktop left
    <action name="SendToDesktopLeft"><dialog>no</dialog><wrap>no</wrap><follow>no</follow></action>
  </keybind>
    <keybind key="W-S-p">             # send window to desktop left
    <action name="SendToDesktopLeft"><dialog>no</dialog><wrap>no</wrap><follow>no</follow></action>
  </keybind>
    <keybind key="S-A-Right">         # send window to desktop right
    <action name="SendToDesktopRight"><dialog>no</dialog><wrap>no</wrap><follow>no</follow></action>
  </keybind>
    <keybind key="W-S-n">             # send window to desktop right
    <action name="SendToDesktopRight"><dialog>no</dialog><wrap>no</wrap><follow>no</follow></action>
  </keybind>
    <keybind key="W-C-p">             # send window to desktop left and move there
    <action name="SendToDesktopLeft"><dialog>no</dialog><wrap>no</wrap><follow>yes</follow></action>
  </keybind>
    <keybind key="W-C-n">             # send window to desktop right and move there
    <action name="SendToDesktopRight"><dialog>no</dialog><wrap>no</wrap><follow>yes</follow></action>
  </keybind>
    <keybind key="S-A-Up">            # send window to desktop up
    <action name="SendToDesktopUp"><dialog>no</dialog><wrap>no</wrap><follow>no</follow></action>
  </keybind>
    <keybind key="S-A-Down">          # send window to desktop down
    <action name="SendToDesktopDown"><dialog>no</dialog><wrap>no</wrap><follow>no</follow></action>
  </keybind>
    <keybind key="W-F1">              # move to desktop 1
    <action name="Desktop"><desktop>1</desktop></action>
  </keybind>
    <keybind key="W-F2">              # move to desktop 2
    <action name="Desktop"><desktop>2</desktop></action>
  </keybind>
    <keybind key="W-F3">              # move to desktop 3
    <action name="Desktop"><desktop>3</desktop></action>
  </keybind>
    <keybind key="W-F4">              # move to desktop 4
    <action name="Desktop"><desktop>4</desktop></action>
  </keybind>
    <keybind key="C-A-d">             # show/hide desktop
    <action name="ToggleShowDesktop"/>
  </keybind>
  <!-- Keybindings for windows -->
  <keybind key="A-F4">              # close active window
    <action name="Close"/>
  </keybind>
  <keybind key="A-Escape">          # lower current window and focus to bottom
      <action name="Lower"/>
      <action name="FocusToBottom"/>
      <action name="Unfocus"/>
    </keybind>
    <keybind key="A-space">           # show the window menu
      <action name="ShowMenu"><menu>client-menu</menu></action>
    </keybind>
    <!-- Keybindings for window switching -->
    <keybind key="A-Tab">             # activate the next window
      <action name="NextWindow"><dialog>list</dialog></action>
    </keybind>
    <keybind key="A-S-Tab">           # activate the previous window
      <action name="PreviousWindow"><dialog>list</dialog></action>
    </keybind>
    <!-- Keybindings for moving focus to windows without raising them -->
    <keybind key="C-A-Tab">           # send focus to the next window
      <action name="NextWindow"><dialog>icons</dialog><finalactions><action name="Focus"/></finalactions></action>
    </keybind>
    <keybind key="C-A-S-Tab">         # send focus to the previous window
      <action name="PreviousWindow"><dialog>icons</dialog><finalactions><action name="Focus"/></finalactions></action>
    </keybind>
    <!-- Focusing and Raising windows -->
    <keybind key="W-u">               #  lower current window focus to bottom
        <action name="Lower"/>
        <action name="Unfocus"/>
        <action name="FocusToBottom"/>
    </keybind>
    <keybind key="W-S-u">             # lower current window without unfocusing
        <action name="Lower"/>
    </keybind>
    <keybind key="W-C-u">             # lower and unfocus current window
        <action name="Lower"/>
        <action name="Unfocus"/>
    </keybind>
    <keybind key="W-i">               # raise the focused window
        <action name="Raise"/>
    </keybind>
    <!-- Keybindings for window tiling -->
    <keybind key="W-h">               # Maximize horizontally or move to left half
      <action name="If"><query target="default"><maximizedhorizontal>yes</maximizedhorizontal></query><then><action name="Unmaximize"><direction>horizontal</direction></action><action name="MoveResizeTo"><x>0</x><width>50%</width></action></then><else><action name="Maximize"><direction>horizontal</direction></action></else></action>
    </keybind>
    <keybind key="W-S-h">             # HalfLeftScreen
      <action name="If"><query><monitor>1</monitor></query><then><action name="UnmaximizeFull"/><action name="MoveResizeTo"><x>0</x><y>0</y><width>50%</width><monitor>1</monitor></action></then><else><action name="UnmaximizeFull"/><action name="MoveResizeTo"><x>0</x><y>0</y><width>50%</width><monitor>2</monitor></action></else></action>
      <action name="Maximize"><direction>vertical</direction></action>
    </keybind>
    <keybind key="W-l">               # Maximize horizontally or move to right half
      <action name="If"><query target="default"><maximizedhorizontal>yes</maximizedhorizontal></query><then><action name="Unmaximize"><direction>horizontal</direction></action><action name="MoveResizeTo"><x>-0</x><width>50%</width></action></then><else><action name="Maximize"><direction>horizontal</direction></action></else></action>
    </keybind>
    <keybind key="W-S-l">             # HalfRightScreen
      <action name="If"><query><monitor>1</monitor></query><then><action name="UnmaximizeFull"/><action name="MoveResizeTo"><x>-0</x><y>0</y><width>50%</width><monitor>1</monitor></action></then><else><action name="UnmaximizeFull"/><action name="MoveResizeTo"><x>-0</x><y>0</y><width>50%</width><monitor>2</monitor></action></else></action>
      <action name="Maximize"><direction>vertical</direction></action>
    </keybind>
    <keybind key="W-j">               # Maximize vertically or move to lower half
      <action name="If"><query target="default"><maximizedvertical>yes</maximizedvertical></query><then><action name="If"><query><monitor>1</monitor></query><then><action name="Unmaximize"><direction>vertical</direction></action><action name="MoveResizeTo"><y>-0</y><height>50%</height><monitor>1</monitor></action></then><else><action name="Unmaximize"><direction>vertical</direction></action><action name="MoveResizeTo"><y>-0</y><height>50%</height><monitor>2</monitor></action></else></action></then><else><action name="Maximize"><direction>vertical</direction></action></else></action>
    </keybind>
    <keybind key="W-S-j">             # HalfLowerScreen
      <action name="If"><query><monitor>1</monitor></query><then><action name="UnmaximizeFull"/><action name="MoveResizeTo"><x>0</x><y>-0</y><width>50%</width><monitor>1</monitor></action></then><else><action name="UnmaximizeFull"/><action name="MoveResizeTo"><x>0</x><y>-0</y><width>50%</width><monitor>2</monitor></action></else></action>
      <action name="Maximize"><direction>horizontal</direction></action>
    </keybind>
    <keybind key="W-k">               # Maximize vertically or move to upper half
      <action name="If"><query target="default"><maximizedvertical>yes</maximizedvertical></query><then><action name="If"><query><monitor>1</monitor></query><then><action name="Unmaximize"><direction>vertical</direction></action><action name="MoveResizeTo"><y>0</y><height>50%</height><monitor>1</monitor></action></then><else><action name="Unmaximize"><direction>vertical</direction></action><action name="MoveResizeTo"><y>0</y><height>50%</height><monitor>2</monitor></action></else></action></then><else><action name="Maximize"><direction>vertical</direction></action></else></action>
    </keybind>
    <keybind key="W-S-k">             # HalfUpperScreen
      <action name="If"><query><monitor>1</monitor></query><then><action name="UnmaximizeFull"/><action name="MoveResizeTo"><x>0</x><y>0</y><width>50%</width><monitor>1</monitor></action></then><else><action name="UnmaximizeFull"/><action name="MoveResizeTo"><x>0</x><y>0</y><width>50%</width><monitor>2</monitor></action></else></action>
      <action name="Maximize"><direction>horizontal</direction></action>
    </keybind>
    <!-- Keybindings for resizing windows -->
    <keybind key="W-w">
      <keybind key="h">               # Grow to edge west W-w-h
        <action name="If"><query target="default"><maximizedhorizontal>yes</maximizedhorizontal></query><then><action name="Unmaximize"><direction>horizontal</direction></action><action name="MoveResizeTo"><width>100%</width></action></then></action>
        <action name="GrowToEdge"><direction>west</direction></action>
      </keybind>
      <keybind key="l">               # Grow to edge east W-w-l
        <action name="If"><query target="default"><maximizedhorizontal>yes</maximizedhorizontal></query><then><action name="Unmaximize"><direction>horizontal</direction></action><action name="MoveResizeTo"><width>100%</width></action></then></action>
        <action name="GrowToEdge"><direction>east</direction></action>
      </keybind>
      <keybind key="j">               # Grow to edge south W-w-j
        <action name="If"><query target="default"><maximizedvertical>yes</maximizedvertical></query><then><action name="Unmaximize"><direction>vertical</direction></action><action name="MoveResizeTo"><width>100%</width></action></then></action>
        <action name="GrowToEdge"><direction>south</direction></action>
      </keybind>
      <keybind key="k">               # Grow to edge north W-w-k
        <action name="If"><query target="default"><maximizedvertical>yes</maximizedvertical></query><then><action name="Unmaximize"><direction>vertical</direction></action><action name="MoveResizeTo"><width>100%</width></action></then></action>
        <action name="GrowToEdge"><direction>north</direction></action>
      </keybind>
      <keybind key="S-h">               # Shrink to edge west W-w-h
        <action name="If"><query target="default"><maximizedhorizontal>yes</maximizedhorizontal></query><then><action name="Unmaximize"><direction>horizontal</direction></action><action name="MoveResizeTo"><width>100%</width></action></then></action>
        <action name="ShrinkToEdge"><direction>west</direction></action>
      </keybind>
      <keybind key="S-l">               # Shrink to edge east W-w-l
        <action name="If"><query target="default"><maximizedhorizontal>yes</maximizedhorizontal></query><then><action name="Unmaximize"><direction>horizontal</direction></action><action name="MoveResizeTo"><width>100%</width></action></then></action>
        <action name="ShrinkToEdge"><direction>east</direction></action>
      </keybind>
      <keybind key="S-j">               # Shrink to edge south W-w-j
        <action name="If"><query target="default"><maximizedvertical>yes</maximizedvertical></query><then><action name="Unmaximize"><direction>vertical</direction></action><action name="MoveResizeTo"><width>100%</width></action></then></action>
        <action name="ShrinkToEdge"><direction>south</direction></action>
      </keybind>
      <keybind key="S-k">               # Shrink to edge north W-w-k
        <action name="If"><query target="default"><maximizedvertical>yes</maximizedvertical></query><then><action name="Unmaximize"><direction>vertical</direction></action><action name="MoveResizeTo"><width>100%</width></action></then></action>
        <action name="ShrinkToEdge"><direction>north</direction></action>
      </keybind>
    </keybind>
    <keybind key="W-e">             # UnmaximizeFull in the same Monitor
      <action name="If"><query><monitor>1</monitor></query><then><action name="Unmaximize"/><action name="MoveResizeTo"><monitor>1</monitor></action></then><else><action name="Unmaximize"/><action name="MoveResizeTo"><monitor>2</monitor></action></else></action>
    </keybind>
    <keybind key="W-space">             # MaximizeFull
          <action name="Maximize"/>
    </keybind>
    <!-- Keybindings for sending windows to monitors -->
    <keybind key="W-m">               # move to next monitor
      <action name="MoveResizeTo"><monitor>next</monitor></action>
    </keybind>
    <!-- Keybindings for monitors -->
    <keybind key="W-1">               # turn off external monitor, keep the primary
      <action name="Execute"><command>xrandr --output VGA-1 --off --output LVDS-1 --mode 1280x800 --rate 60.05</command></action>
    </keybind>
    <keybind key="W-2">               # turn on 1920x1080 monitor
      <action name="Execute"><command>xrandr --output VGA-1 --mode 1920x1080 --pos 0x0 --rate 60.0 --output LVDS-1 --mode 1280x800 --pos 0x1080 --rate 60.05</command></action>
    </keybind>
    <keybind key="W-S-2">             # 1920x1080 monitor on, LVDS off
      <action name="Execute"><command>xrandr --output VGA-1 --mode 1920x1080 --pos 0x0 --rate 60.0 --output LVDS-1 --off</command></action>
    </keybind>
    <keybind key="W-3">               # turn on 1280x960 monitor
      <action name="Execute"><command>xrandr --output VGA-1 --mode 1280x1024 --pos 0x0 --output LVDS-1 --mode 1280x800 --pos 0x1024 --rate 60.05</command></action>
    </keybind>
    <keybind key="W-S-3">             # 1280x960 monitor on, LVDS off
      <action name="Execute"><command>xrandr --output VGA-1 --mode 1280x1024 --pos 0x0 --output LVDS-1 --off</command></action>
    </keybind>
    <!-- Keybindings for the volume buttons -->
    <keybind key="XF86AudioLowerVolume"> # lower volume
      <action name="Execute"><command>amixer sset Master 5000-</command></action>
      <action name="Execute"><command>amixer sset Headphone 5000-</command></action>
    </keybind>
    <keybind key="XF86AudioRaiseVolume"> # raise volume
      <action name="Execute"><command>amixer sset Master 5000+</command></action>
      <action name="Execute"><command>amixer sset Headphone 5000+</command></action>
    </keybind>
    <keybind key="XF86AudioMute">     # toggle sound
      <action name="Execute"><command>amixer sset Master toggle</command></action>
      <action name="Execute"><command>amixer sset Headphone toggle</command></action>
    </keybind>
    <keybind key="C-XF86AudioLowerVolume"> # mocp - play previous
      <action name="Execute"><command>mocp --previous</command></action>
    </keybind>
    <keybind key="C-XF86AudioRaiseVolume"> # mocp - toggle PAUSE
      <action name="Execute"><command>mocp --toggle-pause</command></action>
    </keybind>
    <keybind key="C-XF86AudioMute">     # mocp - play next
      <action name="Execute"><command>mocp --next</command></action>
    </keybind>
    <keybind key="C-S-XF86AudioLowerVolume"> # mocp - seek back 5sec
      <action name="Execute"><command>mocp --seek -5</command></action>
    </keybind>
    <keybind key="C-S-XF86AudioRaiseVolume"> # mocp - PLAY
      <action name="Execute"><command>mocp --play</command></action>
    </keybind>
    <keybind key="C-S-XF86AudioMute">     # mocp - seek forward 5sec
      <action name="Execute"><command>mocp --seek 5</command></action>
    </keybind>
    <!-- Keybindings for running applications -->
    <keybind key="W-b">               # launch Bibletime
      <action name="Execute"><command>bibletime</command></action>
    </keybind>
    <keybind key="W-c">               # launch the Character map
      <action name="Execute"><command>gucharmap</command></action>
    </keybind>
    <keybind key="W-f">               # launch Firefox
      <action name="Execute"><command>firefox</command></action>
    </keybind>
    <keybind key="W-g">
      <keybind key="a">               # launch galculator W-g-a
        <action name="Execute"><command>galculator</command></action>
      </keybind>
    </keybind>
    <keybind key="W-r">               # launch the application launcher
      <action name="Execute"><command>gmrun</command></action>
    </keybind>
    <keybind key="W-s">               # Launch Skype
      <action name="Execute"><command>skype</command></action>
    </keybind>
    <keybind key="W-t">               # attach to last tmux session in terminal
      <action name="Execute"><command>lxterminal -e tmux -2 new-session -A -s MAIN</command></action>
    </keybind>
    <keybind key="W-S-t">             # Launch Terminal with tmux
      <action name="Execute"><command>lxterminal -e tmux -2</command></action>
    </keybind>
    <keybind key="W-v">               # launch VLC
      <action name="Execute"><command>vlc</command></action>
    </keybind>
    <keybind key="W-x">
      <keybind key="a">               # launch Audacity W-x-a
        <action name="Execute"><command>audacity</command></action>
      </keybind>
      <keybind key="c">               # launch LibreOffice Calc W-x-c
        <action name="Execute"><command>localc</command></action>
      </keybind>
      <keybind key="g">               # launch gymp W-x-g
        <action name="Execute"><command>gimp</command></action>
      </keybind>
      <keybind key="h">               # launch harmonogram.xls in Calc W-x-h
        <action name="Execute"><command>localc ~/harmonogram.xls</command></action>
      </keybind>
      <keybind key="i">               # launch inkscape W-x-i
        <action name="Execute"><command>inkscape</command></action>
      </keybind>
      <keybind key="l">               # launch Pluma W-x-l
        <action name="Execute"><command>pluma</command></action>
      </keybind>
      <keybind key="p">               # launch Praat W-x-p
        <action name="Execute"><command>praat</command></action>
      </keybind>
      <keybind key="r">               # launch Rosegarden with timidity W-x-r
        <action name="Execute"><command>timidity -iA</command></action>
        <action name="Execute"><command>rosegarden</command></action>
      </keybind>
      <keybind key="w">               # launch LibreOffice Writer W-x-w
        <action name="Execute"><command>lowriter</command></action>
      </keybind>
    </keybind>
    <keybind key="W-z">               # launch zathura
      <action name="Execute"><command>zathura</command></action>
    </keybind>
    <!-- undefined W-[qy] -->
    <keybind key="W-q">               # launch
      <action name="Execute"><command/></action>
    </keybind>
    <!--keybindings for LXPanel -->
    <keybind key="A-F2">              # launch the application launcher
      <action name="Execute"><command>gmrun</command></action>
    </keybind>
    <keybind key="C-Escape">          # launch the lxpanel menu
      <action name="Execute"><command>lxpanelctl menu</command></action>
    </keybind>
    <keybind key="A-F1">              # launch the lxpanel menu
      <action name="Execute"><command>lxpanelctl menu</command></action>
    </keybind>
    <keybind key="A-F11">             # toggle active window fullscreen
      <action name="ToggleFullscreen"/>
    </keybind>
    <keybind key="A-C-Delete">        # Launch Task Manager with Ctrl+Alt+Del
      <action name="Execute"><command>lxtask</command></action>
    </keybind>
    <keybind key="C-A-l">             # slock the screen with Ctrl-Alt-L
      <action name="Execute"><command>slock</command></action>
    </keybind>
    <keybind key="C-A-s">             # (s)lock the screen and systemctl suspend
      <action name="Execute"><command>slock</command></action>
      <action name="Execute"><command>systemctl suspend</command></action>
    </keybind>
    <keybind key="Print">             # take a screenshot with PrintScreen
      <action name="Execute"><command>scrot</command></action>
    </keybind>
    <keybind key="A-Print">           # take a screenshot of the focused window
      <!-- <action name="Execute"><command>mate-screenshot -w</command></action> -->
      <action name="Execute"><command>scrot -u</command></action>
    </keybind>
    <keybind key="S-Print">             # select a screenshot with PrintScreen
      <!-- <action name="Execute"><command>mate-screenshot -i</command></action> -->
      <action name="Execute"><command>scrot -s</command></action>
    </keybind>
    <keybind key="XF86Display">       # Launch LXRandR with Fn+Screen
      <action name="Execute"><command>lxrandr</command></action>
    </keybind>
    <keybind key="W-o">               # Reconfigure Openbox
      <action name="Reconfigure"/>
    </keybind>
    <keybind key="W-S-o">             # Edit openbox config file in Gvim
    <action name="Execute"><command>lxterminal -e nvim ~/dotfiles/config/openbox/lxde-rc.xml.sml</command></action>
    </keybind>
    <keybind key="A-S-F4">            # exit Openbox
      <action name="Exit"><prompt>yes</prompt></action>
    </keybind>
    <keybind key="W-d">               # toggle decoration in the current window
      <action name="ToggleDecorations"/>
    </keybind>
    <keybind key="W-S-d">             # toggle decoration in all windows
      <action name="ForEach"><then><action name="ToggleDecorations"/></then></action>
    </keybind>
  </keyboard>
  <mouse>
    <dragThreshold>8</dragThreshold>
    <!-- number of pixels the mouse must move before a drag begins -->
    <doubleClickTime>200</doubleClickTime>
    <!-- in milliseconds (1000 = 1 second) -->
    <screenEdgeWarpTime>400</screenEdgeWarpTime>
    <!-- Time before changing desktops when the pointer touches the edge of the
       screen while moving a window, in milliseconds (1000 = 1 second).
       Set this to 0 to disable warping -->
    <context name="Frame">
      <mousebind button="A-Left" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
      </mousebind>
      <mousebind button="A-Left" action="Click">
        <action name="Unshade"/>
      </mousebind>
      <mousebind button="A-Left" action="Drag">
        <action name="If">
          <query target="default">
            <maximized>yes</maximized>
          </query>
          <then>
            <action name="Unmaximize"/>
          </then>
        </action>
        <action name="Move"/>
      </mousebind>
      <mousebind button="A-Right" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
        <action name="Unshade"/>
      </mousebind>
      <mousebind button="A-Right" action="Drag">
        <action name="Resize"/>
      </mousebind>
      <mousebind button="A-Middle" action="Press">
        <action name="Lower"/>
        <action name="FocusToBottom"/>
        <action name="Unfocus"/>
      </mousebind>
      <mousebind button="A-Up" action="Click">
        <action name="DesktopPrevious"/>
      </mousebind>
      <mousebind button="A-Down" action="Click">
        <action name="DesktopNext"/>
      </mousebind>
      <mousebind button="C-A-Up" action="Click">
        <action name="DesktopPrevious"/>
      </mousebind>
      <mousebind button="C-A-Down" action="Click">
        <action name="DesktopNext"/>
      </mousebind>
      <mousebind button="A-S-Up" action="Click">
        <action name="SendToDesktopPrevious"/>
      </mousebind>
      <mousebind button="A-S-Down" action="Click">
        <action name="SendToDesktopNext"/>
      </mousebind>
    </context>
    <context name="Titlebar">
      <mousebind button="Left" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
      </mousebind>
      <mousebind button="Left" action="Drag">
        <action name="If">
          <query target="default">
            <maximized>yes</maximized>
          </query>
          <then>
            <action name="Unmaximize"/>
          </then>
        </action>
        <action name="Move"/>
      </mousebind>
      <mousebind button="Left" action="DoubleClick">
        <action name="ToggleMaximizeFull"/>
      </mousebind>
      <mousebind button="Middle" action="Press">
        <action name="Lower"/>
        <action name="FocusToBottom"/>
        <action name="Unfocus"/>
      </mousebind>
      <mousebind button="Up" action="Click">
        <action name="Shade"/>
        <action name="FocusToBottom"/>
        <action name="Unfocus"/>
        <!--        <action name="Lower"/>        -->
      </mousebind>
      <mousebind button="Down" action="Click">
        <action name="Unshade"/>
        <action name="Raise"/>
      </mousebind>
      <mousebind button="Right" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
        <action name="ShowMenu">
          <menu>client-menu</menu>
        </action>
      </mousebind>
    </context>
    <context name="Top">
      <mousebind button="Left" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
        <action name="Unshade"/>
      </mousebind>
      <mousebind button="Left" action="Drag">
        <action name="Resize">
          <edge>top</edge>
        </action>
      </mousebind>
    </context>
    <context name="Left">
      <mousebind button="Left" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
      </mousebind>
      <mousebind button="Left" action="Drag">
        <action name="Resize">
          <edge>left</edge>
        </action>
      </mousebind>
    </context>
    <context name="Right">
      <mousebind button="Left" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
      </mousebind>
      <mousebind button="Left" action="Drag">
        <action name="Resize">
          <edge>right</edge>
        </action>
      </mousebind>
    </context>
    <context name="Bottom">
      <mousebind button="Left" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
      </mousebind>
      <mousebind button="Left" action="Drag">
        <action name="Resize">
          <edge>bottom</edge>
        </action>
      </mousebind>
      <mousebind button="Middle" action="Press">
        <action name="Lower"/>
        <action name="FocusToBottom"/>
        <action name="Unfocus"/>
      </mousebind>
      <mousebind button="Right" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
        <action name="ShowMenu">
          <menu>client-menu</menu>
        </action>
      </mousebind>
    </context>
    <context name="BLCorner">
      <mousebind button="Left" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
      </mousebind>
      <mousebind button="Left" action="Drag">
        <action name="Resize"/>
      </mousebind>
    </context>
    <context name="BRCorner">
      <mousebind button="Left" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
      </mousebind>
      <mousebind button="Left" action="Drag">
        <action name="Resize"/>
      </mousebind>
    </context>
    <context name="TLCorner">
      <mousebind button="Left" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
        <action name="Unshade"/>
      </mousebind>
      <mousebind button="Left" action="Drag">
        <action name="Resize"/>
      </mousebind>
    </context>
    <context name="TRCorner">
      <mousebind button="Left" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
        <action name="Unshade"/>
      </mousebind>
      <mousebind button="Left" action="Drag">
        <action name="Resize"/>
      </mousebind>
    </context>
    <context name="Client">
      <mousebind button="Left" action="Press">
        <action name="Focus"/>
        <!--        <action name="Raise"/>        -->
      </mousebind>
      <mousebind button="Middle" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
      </mousebind>
      <mousebind button="Right" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
      </mousebind>
    </context>
    <context name="Icon">
      <mousebind button="Left" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
        <action name="Unshade"/>
        <action name="ShowMenu">
          <menu>client-menu</menu>
        </action>
      </mousebind>
      <mousebind button="Right" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
        <action name="ShowMenu">
          <menu>client-menu</menu>
        </action>
      </mousebind>
    </context>
    <context name="AllDesktops">
      <mousebind button="Left" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
        <action name="Unshade"/>
      </mousebind>
      <mousebind button="Left" action="Click">
        <action name="ToggleOmnipresent"/>
      </mousebind>
    </context>
    <context name="Shade">
      <mousebind button="Left" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
      </mousebind>
      <mousebind button="Left" action="Click">
        <action name="ToggleShade"/>
      </mousebind>
    </context>
    <context name="Iconify">
      <mousebind button="Left" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
      </mousebind>
      <mousebind button="Left" action="Click">
        <action name="Iconify"/>
      </mousebind>
    </context>
    <context name="Maximize">
      <mousebind button="Left" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
        <action name="Unshade"/>
      </mousebind>
      <mousebind button="Middle" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
        <action name="Unshade"/>
      </mousebind>
      <mousebind button="Right" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
        <action name="Unshade"/>
      </mousebind>
      <mousebind button="Left" action="Click">
        <action name="ToggleMaximizeFull"/>
      </mousebind>
      <mousebind button="Middle" action="Click">
        <action name="ToggleMaximizeVert"/>
      </mousebind>
      <mousebind button="Right" action="Click">
        <action name="ToggleMaximizeHorz"/>
      </mousebind>
    </context>
    <context name="Close">
      <mousebind button="Left" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
        <action name="Unshade"/>
      </mousebind>
      <mousebind button="Left" action="Click">
        <action name="Close"/>
      </mousebind>
    </context>
    <context name="Desktop">
      <mousebind button="Up" action="Click">
        <action name="DesktopPrevious"/>
      </mousebind>
      <mousebind button="Down" action="Click">
        <action name="DesktopNext"/>
      </mousebind>
      <mousebind button="A-Up" action="Click">
        <action name="DesktopPrevious"/>
      </mousebind>
      <mousebind button="A-Down" action="Click">
        <action name="DesktopNext"/>
      </mousebind>
      <mousebind button="C-A-Up" action="Click">
        <action name="DesktopPrevious"/>
      </mousebind>
      <mousebind button="C-A-Down" action="Click">
        <action name="DesktopNext"/>
      </mousebind>
      <mousebind button="Left" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
      </mousebind>
      <mousebind button="Right" action="Press">
        <action name="Focus"/>
        <action name="Raise"/>
      </mousebind>
    </context>
    <context name="Root">
      <!-- Menus -->
      <mousebind button="Middle" action="Press">
        <action name="ShowMenu">
          <menu>client-list-combined-menu</menu>
        </action>
      </mousebind>
      <mousebind button="Right" action="Press">
        <action name="ShowMenu">
          <menu>root-menu</menu>
        </action>
      </mousebind>
    </context>
    <context name="MoveResize">
      <mousebind button="Up" action="Click">
        <action name="DesktopPrevious"/>
      </mousebind>
      <mousebind button="Down" action="Click">
        <action name="DesktopNext"/>
      </mousebind>
      <mousebind button="A-Up" action="Click">
        <action name="DesktopPrevious"/>
      </mousebind>
      <mousebind button="A-Down" action="Click">
        <action name="DesktopNext"/>
      </mousebind>
    </context>
  </mouse>
  <menu>
    <!-- You can specify more than one menu file in here and they are all loaded,
       just don't make menu ids clash or, well, it'll be kind of pointless -->

  <!-- default menu file (or custom one in $HOME/.config/openbox/) -->
  <file>/usr/share/lxde/openbox/menu.xml</file>
  <hideDelay>200</hideDelay>
  <!-- if a press-release lasts longer than this setting (in milliseconds), the
       menu is hidden again -->
  <middle>no</middle>
  <!-- center submenus vertically about the parent entry -->
  <submenuShowDelay>25</submenuShowDelay>
  <!-- this one is easy, time to delay before showing a submenu after hovering
       over the parent entry -->
  <applicationIcons>yes</applicationIcons>
  <!-- controls if icons appear in the client-list-(combined-)menu -->
  <manageDesktops>yes</manageDesktops>
  <!-- show the manage desktops section in the client-list-(combined-)menu -->
</menu>

<applications>
  <!-- <application type="normal"> -->
  <!--   <decor>no</decor> -->
    <!-- </application> -->
    <application name="lowriter">
      <maximized>true</maximized>
    </application>
    <application name="zathura">
      <maximized>true</maximized>
      <focus>true</focus>
    </application>
    <application name="mupdf">
      <maximized>true</maximized>
      <focus>true</focus>
    </application>
    <!--
  # this is an example with comments through out. use these to make your
  # own rules, but without the comments of course.

  <application name="first element of window's WM_CLASS property (see xprop)"
              class="second element of window's WM_CLASS property (see xprop)"
               role="the window's WM_WINDOW_ROLE property (see xprop)">
  # the name or the class can be set, or both. this is used to match
  # windows when they appear. role can optionally be set as well, to
  # further restrict your matches.

  # the name, class, and role use simple wildcard matching such as those
  # used by a shell. you can use * to match any characters and ? to match
  # any single character.

  # when multiple rules match a window, they will all be applied, in the
  # order that they appear in this list


    # each element can be left out or set to 'default' to specify to not
    # change that attribute of the window

    <decor>yes</decor>
    # enable or disable window decorations

    <shade>no</shade>
    # make the window shaded when it appears, or not

    <position>
      # the position is only used if both an x and y coordinate are provided
      # (and not set to 'default')
      <x>center</x>
      # a number like 50, or 'center' to center on screen. use a negative number
      # to start from the right (or bottom for <y>), ie -50 is 50 pixels from the
      # right edge (or bottom).
      <y>200</y>
      <monitor>1</monitor>
      # specifies the monitor in a xinerama setup.
      # 1 is the first head, or 'mouse' for wherever the mouse is
    </position>

    <focus>yes</focus>
    # if the window should try be given focus when it appears. if this is set
    # to yes it doesn't guarantee the window will be given focus. some
    # restrictions may apply, but Openbox will try to

    <desktop>1</desktop>
    # 1 is the first desktop, 'all' for all desktops

    <layer>normal</layer>
    # 'above', 'normal', or 'below'

    <iconic>no</iconic>
    # make the window iconified when it appears, or not

    <skip_pager>no</skip_pager>
    # asks to not be shown in pagers

    <skip_taskbar>no</skip_taskbar>
    # asks to not be shown in taskbars. window cycling actions will also
    # skip past such windows

    <fullscreen>yes</fullscreen>
    # make the window in fullscreen mode when it appears

    <maximized>true</maximized>
    # 'Horizontal', 'Vertical' or boolean (yes/no)
  </application>

  # end of the example
-->
</applications>

</openbox_config>
